/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./models/d014.glb --types --exportdefault --output=./gltf/d014.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useRef, useMemo, useImperativeHandle } from 'react';
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'd014_act0' | 'd014_act1' | 'd014_act10' | 'd014_act11' | 'd014_act2' | 'd014_act3' | 'd014_act4' | 'd014_act5' | 'd014_act6' | 'd014_act7' | 'd014_act8' | 'd014_act9'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    d014: THREE.SkinnedMesh
    root: THREE.Bone
  }
  materials: {
    d014: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

export default React.forwardRef(function d014(props: JSX.IntrinsicElements['group'], ref: React.Ref<{ actions: any }>) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/models/d014.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
        // Expose actions to the parent via the ref
      useImperativeHandle(ref, () => ({ actions }));
        return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="d014_armature">
          <primitive object={nodes.root} />
        </group>
        <skinnedMesh name="d014" geometry={nodes.d014.geometry} material={materials.d014} skeleton={nodes.d014.skeleton} />
      </group>
    </group>
    ); })

useGLTF.preload('/models/d014.glb')
