export const AREA_NAMES = {
  0: "???",
  1: "{Term Balamb}: Alcauld Plains",
  2: "{Term Balamb}: Gaulg Mountains",
  3: "{Term Balamb}: Rinaul Coast",
  4: "{Term Balamb}: Raha Cape",
  5: "{Term Timber}: Roshfall Forest",
  6: "{Term Timber}: Mandy Beach",
  7: "{Term Timber}: Obel Lake",
  8: "{Term Timber}: Lanker Plains",
  9: "{Term Timber}: Nanchucket Island",
  10: "{Term Timber}: Yaulny Canyon",
  11: "{Term Dollet}: Hasberry Plains",
  12: "{Term Dollet}: Holy Glory Cape",
  13: "{Term Dollet}: Long Horn Island",
  14: "{Term Dollet}: Malgo Peninsula",
  15: "{Term Galbadia}: Monterosa Plateau",
  16: "{Term Galbadia}: Lallapalooza Canyon",
  17: "{Term Timber}: Shenand Hill",
  18: "{Term Galbadia}: Gotland Peninsula",
  19: "Island Closest to Hell",
  20: "Great Plains of {Term Galbadia}",
  21: "{Term Galbadia}: Wilburn Hill",
  22: "{Term Galbadia}: Rem Archipelago",
  23: "{Term Galbadia}: Dingo Desert",
  24: "Winhill: Winhill Bluffs",
  25: "Winhill: Humphrey Archipelago",
  26: "{Term Trabia}: Winter Island",
  27: "{Term Trabia}: Sorbald Snowfield",
  28: "{Term Trabia}: Eldbeak Peninsula",
  29: "               ",
  30: "{Term Trabia}: Hawkwind Plains",
  31: "{Term Trabia}: Albatross Archipelago",
  32: "{Term Trabia}: Bika Snowfield",
  33: "{Term Trabia}: Thor Peninsula",
  34: "               ",
  35: "{Term Trabia}: Heath Peninsula",
  36: "{Term Trabia}: {Term Trabia} Crater",
  37: "{Term Trabia}: Vienne Mountains",
  38: "{Term Esthar}: Mordred Plains",
  39: "{Term Esthar}: Nortes Mountains",
  40: "{Term Esthar}: Fulcura Archipelago",
  41: "{Term Esthar}: Grandidi Forest",
  42: "{Term Esthar}: Millefeuille Archipelago",
  43: "Great Plains of {Term Esthar}",
  44: "{Term Esthar} City",
  45: "{Term Esthar}: Great Salt Lake",
  46: "{Term Esthar}: West Coast",
  47: "{Term Esthar}: Sollet Mountains",
  48: "{Term Esthar}: Abadan Plains",
  49: "{Term Esthar}: Minde Island",
  50: "{Term Esthar}: Kashkabald Desert",
  51: "Island Closest to Heaven",
  52: "{Term Esthar}: Talle Mountains",
  53: "{Term Esthar}: Shalmal Peninsula",
  54: "{Term Centra}: Lolestern Plains",
  55: "{Term Centra}: Almaj Mountains",
  56: "{Term Centra}: Lenown Plains",
  57: "{Term Centra}: Cape of Good Hope",
  58: "{Term Centra}: Yorn Mountains",
  59: "{Term Esthar}: Cactuar Island",
  60: "{Term Centra}: Serengetti Plains",
  61: "{Term Centra}: Nectar Peninsula",
  62: "{Term Centra}: {Term Centra} Crater",
  63: "{Term Centra}: Poccarahi Island",
  64: "B-{Term Garden}: Library",
  65: "B-{Term Garden}: Front Gate",
  66: "B-{Term Garden}: Classroom",
  67: "B-{Term Garden}: Cafeteria",
  68: "B-{Term Garden}: MD Level",
  69: "B-{Term Garden}: 2F Hallway",
  70: "B-{Term Garden}: Hall",
  71: "B-{Term Garden}: Infirmary",
  72: "B-{Term Garden}: Dormitory Double",
  73: "B-{Term Garden}: Dormitory Single",
  74: "B-{Term Garden}: Headmaster’s Office",
  75: "B-{Term Garden}: Parking Lot",
  76: "B-{Term Garden}: Ballroom",
  77: "B-{Term Garden}: Quad",
  78: "B-{Term Garden}: Training Center",
  79: "B-{Term Garden}: Secret Area",
  80: "B-{Term Garden}: Hallway",
  81: "B-{Term Garden}: Master Room",
  82: "B-{Term Garden}: Deck",
  83: "{Term Balamb}: The Dincht’s",
  84: "{Term Balamb} Hotel",
  85: "{Term Balamb}: Town Square",
  86: "{Term Balamb}: Station Yard",
  87: "{Term Balamb} Harbor",
  88: "{Term Balamb}: Residence",
  89: "Train",
  90: "Car",
  91: "Inside Ship",
  92: "Fire Cavern",
  93: "{Term Dollet}: Town Square",
  94: "{Term Dollet}: Lapin Beach",
  95: "{Term Dollet} Harbor",
  96: "{Term Dollet} Pub",
  97: "{Term Dollet} Hotel",
  98: "{Term Dollet}: Residence",
  99: "{Term Dollet}: Comm Tower",
  100: "{Term Dollet}: Mountain Hideout",
  101: "{Term Timber}: City Square",
  102: "{Term Timber} TV Station",
  103: "{Term Timber}: Forest Owls’ Base",
  104: "{Term Timber} Pub",
  105: "{Term Timber} Hotel",
  106: "{Term Timber}: Train",
  107: "{Term Timber}: Residence",
  108: "{Term Timber}: TV Screen",
  109: "{Term Timber}: Editorial Department",
  110: "{Term Timber} Forest",
  111: "{Term Galbadia} {Term Garden}: Front Gate",
  112: "G-{Term Garden}: Station",
  113: "G-{Term Garden}: Hall",
  114: "G-{Term Garden}: Hallway",
  115: "G-{Term Garden}: Reception Room",
  116: "G-{Term Garden}: Classroom",
  117: "G-{Term Garden}: Clubroom",
  118: "G-{Term Garden}: Dormitory",
  119: "G-{Term Garden}: Elevator Hall",
  120: "G-{Term Garden}: Master Room",
  121: "G-{Term Garden}: Auditorium",
  122: "G-{Term Garden}: Athletic Track",
  123: "G-{Term Garden}: Stand",
  124: "G-{Term Garden}: Back Entrance",
  125: "G-{Term Garden}: Gymnasium",
  126: "{Term Deling}: Presidential Residence",
  127: "{Term DelingCity}: Caraway’s Mansion",
  128: "{Term DelingCity}: Station Yard",
  129: "{Term DelingCity}: City Square",
  130: "{Term DelingCity}: Hotel",
  131: "{Term DelingCity}: Club",
  132: "{Term DelingCity}: Gateway",
  133: "{Term DelingCity}: Parade",
  134: "{Term DelingCity}: Sewer",
  135: "{Term Galbadia} D-District Prison",
  136: "Desert",
  137: "{Term Galbadia} Missile Base",
  138: "Winhill Village",
  139: "Winhill Pub",
  140: "Winhill- Vacant House",
  141: "Winhill- Mansion",
  142: "Winhill- Residence",
  143: "Winhill- Hotel",
  144: "Winhill- Car",
  145: "Tomb of the Unknown King",
  146: "{Term FishermansHorizon}",
  147: "FH: Residential Area",
  148: "FH: Sun Panel",
  149: "FH: Mayor’s Residence",
  150: "FH: Factory",
  151: "FH: Festival Grounds",
  152: "FH: Hotel",
  153: "FH: Residence",
  154: "FH: Station Yard",
  155: "Horizon Bridge",
  156: "Seaside Station",
  157: "Great Salt Lake",
  158: "Mystery Building",
  159: "{Term Esthar}: City",
  160: "{Term Esthar}: Odine’s Laboratory",
  161: "{Term Esthar}: Airstation",
  162: "Lunatic Pandora Approaching",
  163: "{Term Esthar}: Presidential Palace",
  164: "Presidential Palace: Hall",
  165: "Presidential Palace: Hallway",
  166: "Presidential Palace: Office",
  167: "Dr. Odine’s Laboratory: Lobby",
  168: "Dr. Odine’s Laboratory: Lab",
  169: "Deleted",
  170: "{Term LunarGate}",
  171: "{Term LunarGate}: Concourse",
  172: "{Term LunarGate}: Deep Freeze",
  173: "{Term Esthar} Sorceress Memorial",
  174: "Sorceress Memorial: Entrance",
  175: "Sorceress Memorial: Pod",
  176: "Sorceress Memorial: Ctrl Room",
  177: "Tears’ Point",
  178: "Lunatic Pandora Laboratory",
  179: "Emergency Landing Zone",
  180: "Spaceship Landing Zone",
  181: "Lunatic Pandora",
  182: "{Term Centra}: Excavation Site",
  183: "Edea’s House",
  184: "Edea’s House: Playroom",
  185: "Edea’s House: Bedroom",
  186: "Edea’s House: Backyard",
  187: "Edea’s House: Oceanside",
  188: "Edea’s House: Flower Field",
  189: "{Term Centra} Ruins",
  190: "{Term Trabia} {Term Garden}: Front Gate",
  191: "T-{Term Garden}: Cemetery",
  192: "T-{Term Garden}: Garage",
  193: "T-{Term Garden}: Festival Stage",
  194: "T-{Term Garden}: Classroom",
  195: "T-{Term Garden}: Athletic Ground",
  196: "Mystery Dome",
  197: "{Term ShumiVillage}: Desert Village",
  198: "{Term ShumiVillage}: Elevator",
  199: "{Term ShumiVillage}: Village",
  200: "{Term ShumiVillage}: Residence",
  201: "{Term ShumiVillage}: Residence",
  202: "{Term ShumiVillage}: Residence",
  203: "{Term ShumiVillage}: Hotel",
  204: "{Term Trabia} Canyon",
  205: "White SeeD Ship",
  206: "White SeeD Ship",
  207: "White SeeD Ship: Cabin",
  208: "Ragnarok: Cockpit",
  209: "Ragnarok: Passenger Seat",
  210: "Ragnarok: Aisle",
  211: "Ragnarok: Hangar",
  212: "Ragnarok: Entrance",
  213: "Ragnarok: Air Room",
  214: "Ragnarok: Space Hatch",
  215: "Deep Sea Research Center",
  216: "Deep Sea Research Center: Lb",
  217: "Deep Sea Research Center: Lv",
  218: "Deep Sea Deposit",
  219: "{Term LunarBase}: Control Room",
  220: "{Term LunarBase}: Medical Room",
  221: "{Term LunarBase}: Pod",
  222: "{Term LunarBase}: Dock",
  223: "{Term LunarBase}: Passageway",
  224: "{Term LunarBase}: Locker",
  225: "{Term LunarBase}: Residential Zone",
  226: "Outer Space",
  227: "Chocobo Forest",
  228: "Wilderness",
  229: "{Term UltimeciaCastle}: Hall",
  230: "{Term UltimeciaCastle}: Grand Hall",
  231: "{Term UltimeciaCastle}: Terrace",
  232: "{Term UltimeciaCastle}: Wine Cellar",
  233: "{Term UltimeciaCastle}: Passageway",
  234: "{Term UltimeciaCastle}: Elevator Hall",
  235: "{Term UltimeciaCastle}: Stairway Hall",
  236: "{Term UltimeciaCastle}: Treasure Rm",
  237: "{Term UltimeciaCastle}: Storage Room",
  238: "{Term UltimeciaCastle}: Art Gallery",
  239: "{Term UltimeciaCastle}: Flood Gate",
  240: "{Term UltimeciaCastle}: Armory",
  241: "{Term UltimeciaCastle}: Prison Cell",
  242: "{Term UltimeciaCastle}: Waterway",
  243: "{Term UltimeciaCastle}: Courtyard",
  244: "{Term UltimeciaCastle}: Chapel",
  245: "{Term UltimeciaCastle}: Clock Tower",
  246: "{Term UltimeciaCastle}: Master Room",
  247: "???",
  248: "{Term UltimeciaCastle}",
  249: "Commencement Room",
  250: "Queen"
} as const;