/* eslint-disable */
// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/d001.gltf --types --keepgroups --exportdefault --output=./gltf/d001.tsx 
*/

import * as THREE from 'three'
import React, { useImperativeHandle } from 'react'
import { useGraph } from '@react-three/fiber'
import { useAnimations } from '@react-three/drei';
import { useFragmentedGLTFLoader } from '../useFragmentedGLTFLoader'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'd001_action_0' | 'd001_action_1' | 'd001_action_2' | 'd001_action_3' | 'd001_action_4'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    d001_mesh: THREE.SkinnedMesh
    d001_mesh_1: THREE.SkinnedMesh
    bone_0: THREE.Bone
  }
  materials: {
    d001_texture_0: THREE.MeshStandardMaterial
    d001_texture_1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default React.forwardRef(function d001(props: JSX.IntrinsicElements['group'], ref: React.Ref<{ actions: Record<ActionName, AnimationAction>, mesh: Group }>) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useFragmentedGLTFLoader('d001', props.mapName)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
    
    const formattedAnimations = useAnimations(animations, group);
    useImperativeHandle(ref, () => ({ animations: formattedAnimations, group, nodes, materials }));
      return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="d001_armature">
          <primitive object={nodes.bone_0} />
          <group name="d001">
            <skinnedMesh name="d001_mesh" geometry={nodes.d001_mesh.geometry} material={materials.d001_texture_0} skeleton={nodes.d001_mesh.skeleton} />
            <skinnedMesh name="d001_mesh_1" geometry={nodes.d001_mesh_1.geometry} material={materials.d001_texture_1} skeleton={nodes.d001_mesh_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
    ); })

useFragmentedGLTFLoader.preload('d001')
