/* eslint-disable */
// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/d007.gltf --types --keepgroups --exportdefault --output=../gltf/d007.tsx 
*/

import * as THREE from 'three'
import React, { useImperativeHandle } from 'react'
import { useGraph } from '@react-three/fiber'
import { useAnimations } from '@react-three/drei';
import { useFragmentedGLTFLoader } from '../useFragmentedGLTFLoader'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'd007_action_0' | 'd007_action_1' | 'd007_action_10' | 'd007_action_11' | 'd007_action_12' | 'd007_action_13' | 'd007_action_2' | 'd007_action_3' | 'd007_action_4' | 'd007_action_5' | 'd007_action_6' | 'd007_action_7' | 'd007_action_8' | 'd007_action_9'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    d007: THREE.SkinnedMesh
    bone_0: THREE.Bone
  }
  materials: {
    d007_texture_0: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default React.forwardRef(function d007(props: JSX.IntrinsicElements['group'], ref: React.Ref<{ actions: Record<ActionName, AnimationAction>, mesh: Group }>) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useFragmentedGLTFLoader('d007', props.mapName)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)

 const formattedAnimations = useAnimations(animations, group);
 useImperativeHandle(ref, () => ({ animations: formattedAnimations, group, nodes, materials }));
   return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="d007_armature" position={[0, 0, 0.933]}>
          <primitive object={nodes.bone_0} />
          <skinnedMesh name="d007" geometry={nodes.d007.geometry} material={materials.d007_texture_0} skeleton={nodes.d007.skeleton} />
        </group>
      </group>
    </group>
 ); })

useFragmentedGLTFLoader.preload('d007')
