/* eslint-disable */
// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/d012.gltf --types --keepgroups --exportdefault --output=../gltf/d012.tsx 
*/

import * as THREE from 'three'
import React, { useImperativeHandle } from 'react'
import { useGraph } from '@react-three/fiber'
import { useAnimations } from '@react-three/drei';
import { useFragmentedGLTFLoader } from '../useFragmentedGLTFLoader'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'd012_action_0' | 'd012_action_1' | 'd012_action_10' | 'd012_action_11' | 'd012_action_12' | 'd012_action_13' | 'd012_action_14' | 'd012_action_15' | 'd012_action_16' | 'd012_action_17' | 'd012_action_18' | 'd012_action_19' | 'd012_action_2' | 'd012_action_20' | 'd012_action_21' | 'd012_action_22' | 'd012_action_23' | 'd012_action_3' | 'd012_action_4' | 'd012_action_5' | 'd012_action_6' | 'd012_action_7' | 'd012_action_8' | 'd012_action_9'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    d012_mesh: THREE.SkinnedMesh
    d012_mesh_1: THREE.SkinnedMesh
    bone_0: THREE.Bone
  }
  materials: {
    d012_texture_0: THREE.MeshStandardMaterial
    d012_texture_1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default React.forwardRef(function d012(props: JSX.IntrinsicElements['group'], ref: React.Ref<{ actions: Record<ActionName, AnimationAction>, mesh: Group }>) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useFragmentedGLTFLoader('d012', props.mapName)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)

 const formattedAnimations = useAnimations(animations, group);
 useImperativeHandle(ref, () => ({ animations: formattedAnimations, group, nodes, materials }));
   return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="d012_armature" position={[0, 0, 0.892]}>
          <primitive object={nodes.bone_0} />
          <group name="d012">
            <skinnedMesh name="d012_mesh" geometry={nodes.d012_mesh.geometry} material={materials.d012_texture_0} skeleton={nodes.d012_mesh.skeleton} />
            <skinnedMesh name="d012_mesh_1" geometry={nodes.d012_mesh_1.geometry} material={materials.d012_texture_1} skeleton={nodes.d012_mesh_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
 ); })

useFragmentedGLTFLoader.preload('d012')
