/* eslint-disable */
// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/d021.gltf --types --keepgroups --exportdefault --output=../gltf/d021.tsx 
*/

import * as THREE from 'three'
import React, { useImperativeHandle } from 'react'
import { useGraph } from '@react-three/fiber'
import { useAnimations } from '@react-three/drei';
import { useFragmentedGLTFLoader } from '../useFragmentedGLTFLoader'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'd021_action_000' | 'd021_action_001' | 'd021_action_002' | 'd021_action_003' | 'd021_action_004' | 'd021_action_005' | 'd021_action_006' | 'd021_action_007' | 'd021_action_008' | 'd021_action_009' | 'd021_action_010' | 'd021_action_011' | 'd021_action_012' | 'd021_action_013' | 'd021_action_014' | 'd021_action_015' | 'd021_action_016' | 'd021_action_017' | 'd021_action_018'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    d021_mesh: THREE.SkinnedMesh
    d021_mesh_1: THREE.SkinnedMesh
    bone_0: THREE.Bone
  }
  materials: {
    d021_texture_0: THREE.MeshStandardMaterial
    d021_texture_1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default React.forwardRef(function d021(props: JSX.IntrinsicElements['group'], ref: React.Ref<{ actions: Record<ActionName, AnimationAction>, mesh: Group }>) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useFragmentedGLTFLoader('d021', props.mapName)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)

 const formattedAnimations = useAnimations(animations, group);
 useImperativeHandle(ref, () => ({ animations: formattedAnimations, group, nodes, materials }));
   return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="d021_armature">
          <primitive object={nodes.bone_0} />
          <group name="d021">
            <skinnedMesh name="d021_mesh" geometry={nodes.d021_mesh.geometry} material={materials.d021_texture_0} skeleton={nodes.d021_mesh.skeleton} />
            <skinnedMesh name="d021_mesh_1" geometry={nodes.d021_mesh_1.geometry} material={materials.d021_texture_1} skeleton={nodes.d021_mesh_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
 ); })

useFragmentedGLTFLoader.preload('d021')
