/* eslint-disable */
// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/d037.gltf --types --keepgroups --exportdefault --output=../gltf/d037.tsx 
*/

import * as THREE from 'three'
import React, { useImperativeHandle } from 'react'
import { useGraph } from '@react-three/fiber'
import { useAnimations } from '@react-three/drei';
import { useFragmentedGLTFLoader } from '../useFragmentedGLTFLoader'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'd037_action_000' | 'd037_action_001' | 'd037_action_002' | 'd037_action_003' | 'd037_action_004' | 'd037_action_005' | 'd037_action_006' | 'd037_action_007' | 'd037_action_008' | 'd037_action_009' | 'd037_action_010' | 'd037_action_011' | 'd037_action_012'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    d037_mesh: THREE.SkinnedMesh
    d037_mesh_1: THREE.SkinnedMesh
    bone_0: THREE.Bone
  }
  materials: {
    d037_texture_0: THREE.MeshStandardMaterial
    d037_texture_1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default React.forwardRef(function d037(props: JSX.IntrinsicElements['group'], ref: React.Ref<{ actions: Record<ActionName, AnimationAction>, mesh: Group }>) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useFragmentedGLTFLoader('d037', props.mapName)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)

 const formattedAnimations = useAnimations(animations, group);
 useImperativeHandle(ref, () => ({ animations: formattedAnimations, group, nodes, materials }));
   return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="d037_armature">
          <primitive object={nodes.bone_0} />
          <group name="d037">
            <skinnedMesh name="d037_mesh" geometry={nodes.d037_mesh.geometry} material={materials.d037_texture_0} skeleton={nodes.d037_mesh.skeleton} />
            <skinnedMesh name="d037_mesh_1" geometry={nodes.d037_mesh_1.geometry} material={materials.d037_texture_1} skeleton={nodes.d037_mesh_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
 ); })

useFragmentedGLTFLoader.preload('d037')
