/* eslint-disable */
// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./optimized/base/models/d045.gltf --types --keepgroups --exportdefault --output=./gltf/d045.tsx 
*/

import * as THREE from 'three'
import React, { useImperativeHandle } from 'react'
import { useGraph } from '@react-three/fiber'
import { useAnimations } from '@react-three/drei';
import { useFragmentedGLTFLoader } from '../useFragmentedGLTFLoader'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'd045_action_000' | 'd045_action_001' | 'd045_action_002' | 'd045_action_003' | 'd045_action_004' | 'd045_action_005' | 'd045_action_006' | 'd045_action_007'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    d045: THREE.SkinnedMesh
    bone_0: THREE.Bone
  }
  materials: {
    d045_texture_0: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default React.forwardRef(function d045(props: JSX.IntrinsicElements['group'], ref: React.Ref<{ actions: Record<ActionName, AnimationAction>, mesh: Group }>) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useFragmentedGLTFLoader('d045', props.mapName)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)

 const formattedAnimations = useAnimations(animations, group);
 useImperativeHandle(ref, () => ({ animations: formattedAnimations, group, nodes, materials }));
   return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="d045_armature">
          <primitive object={nodes.bone_0} />
        </group>
        <skinnedMesh name="d045" geometry={nodes.d045.geometry} material={materials.d045_texture_0} skeleton={nodes.d045.skeleton} />
      </group>
    </group>
 ); })

useFragmentedGLTFLoader.preload('d045')
