/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./models/d049.glb --types --exportdefault --output=./gltf/d049.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useRef, useMemo, useImperativeHandle } from 'react';
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'd049_act0' | 'd049_act1' | 'd049_act2' | 'd049_act3' | 'd049_act4' | 'd049_act5' | 'd049_act6'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    d049: THREE.SkinnedMesh
    root: THREE.Bone
    neutral_bone: THREE.Bone
  }
  materials: {
    d049: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

export default React.forwardRef(function d049(props: JSX.IntrinsicElements['group'], ref: React.Ref<{ actions: any }>) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/models/d049.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
        // Expose actions to the parent via the ref
      useImperativeHandle(ref, () => ({ actions }));
        return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="d049_armature">
          <primitive object={nodes.root} />
          <primitive object={nodes.neutral_bone} />
        </group>
        <skinnedMesh name="d049" geometry={nodes.d049.geometry} material={materials.d049} skeleton={nodes.d049.skeleton} />
      </group>
    </group>
    ); })

useGLTF.preload('/models/d049.glb')
