/* eslint-disable */
// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/d050.gltf --types --keepgroups --exportdefault --output=../gltf/d050.tsx 
*/

import * as THREE from 'three'
import React, { useImperativeHandle } from 'react'
import { useGraph } from '@react-three/fiber'
import { useAnimations } from '@react-three/drei';
import { useFragmentedGLTFLoader } from '../useFragmentedGLTFLoader'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'd050_action_000' | 'd050_action_001' | 'd050_action_002' | 'd050_action_003' | 'd050_action_004' | 'd050_action_005' | 'd050_action_006' | 'd050_action_007' | 'd050_action_008' | 'd050_action_009' | 'd050_action_010' | 'd050_action_011' | 'd050_action_012' | 'd050_action_013' | 'd050_action_014' | 'd050_action_015' | 'd050_action_016' | 'd050_action_017' | 'd050_action_018' | 'd050_action_019'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    d050: THREE.SkinnedMesh
    bone_0: THREE.Bone
  }
  materials: {
    d050_texture_0: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default React.forwardRef(function d050(props: JSX.IntrinsicElements['group'], ref: React.Ref<{ actions: Record<ActionName, AnimationAction>, mesh: Group }>) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useFragmentedGLTFLoader('d050', props.mapName)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)

 const formattedAnimations = useAnimations(animations, group);
 useImperativeHandle(ref, () => ({ animations: formattedAnimations, group, nodes, materials }));
   return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="d050_armature">
          <primitive object={nodes.bone_0} />
          <skinnedMesh name="d050" geometry={nodes.d050.geometry} material={materials.d050_texture_0} skeleton={nodes.d050.skeleton} />
        </group>
      </group>
    </group>
 ); })

useFragmentedGLTFLoader.preload('d050')
