/* eslint-disable */
// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/d050.glb --types --exportdefault --output=./gltf/d050.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'd050_act0' | 'd050_act1' | 'd050_act10' | 'd050_act11' | 'd050_act12' | 'd050_act13' | 'd050_act14' | 'd050_act15' | 'd050_act16' | 'd050_act17' | 'd050_act18' | 'd050_act19' | 'd050_act2' | 'd050_act3' | 'd050_act4' | 'd050_act5' | 'd050_act6' | 'd050_act7' | 'd050_act8' | 'd050_act9'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    d050: THREE.SkinnedMesh
    root: THREE.Bone
  }
  materials: {
    d050: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default React.forwardRef(function d050(props: JSX.IntrinsicElements['group'], ref: React.Ref<{ actions: Record<ActionName, AnimationAction>, mesh: Group }>) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/models/d050.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
    
    const formattedAnimations = useAnimations(animations, group);
    useImperativeHandle(ref, () => ({ animations: formattedAnimations, group, nodes, materials }));
      return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="d050_armature">
          <primitive object={nodes.root} />
        </group>
        <skinnedMesh name="d050" geometry={nodes.d050.geometry} material={materials.d050} skeleton={nodes.d050.skeleton} />
      </group>
    </group>
    ); })

useGLTF.preload('/models/d050.glb')
