/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/d060.glb --types --exportdefault --output=./gltf/d060.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useRef, useMemo, useImperativeHandle } from 'react';
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'd060_act0' | 'd060_act1' | 'd060_act2' | 'd060_act3' | 'd060_act4' | 'd060_act5'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    d060: THREE.SkinnedMesh
    root: THREE.Bone
  }
  materials: {
    d060: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default React.forwardRef(function d060(props: JSX.IntrinsicElements['group'], ref: React.Ref<{ actions: Record<ActionName, AnimationAction>, mesh: Group }>) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/models/d060.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
        // Expose actions to the parent via the ref
      useImperativeHandle(ref, () => ({ actions, group, nodes, materials }));
        return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="d060_armature">
          <primitive object={nodes.root} />
        </group>
        <skinnedMesh name="d060" geometry={nodes.d060.geometry} material={materials.d060} skeleton={nodes.d060.skeleton} />
      </group>
    </group>
    ); })

useGLTF.preload('/models/d060.glb')
