/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/d065.glb --types --exportdefault --output=./gltf/d065.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useRef, useMemo, useImperativeHandle } from 'react';
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'd065_act0' | 'd065_act1' | 'd065_act2' | 'd065_act3' | 'd065_act4' | 'd065_act5' | 'd065_act6'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    d065: THREE.SkinnedMesh
    root: THREE.Bone
  }
  materials: {
    d065: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default React.forwardRef(function d065(props: JSX.IntrinsicElements['group'], ref: React.Ref<{ actions: Record<ActionName, AnimationAction>, mesh: Group }>) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/models/d065.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
        // Expose actions to the parent via the ref
      useImperativeHandle(ref, () => ({ actions, group, nodes, materials }));
        return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="d065_armature">
          <primitive object={nodes.root} />
        </group>
        <skinnedMesh name="d065" geometry={nodes.d065.geometry} material={materials.d065} skeleton={nodes.d065.skeleton} />
      </group>
    </group>
    ); })

useGLTF.preload('/models/d065.glb')
