/* eslint-disable */
// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/n006.glb --types --exportdefault --output=./gltf/n006.tsx 
*/

import * as THREE from 'three'
import React, { useImperativeHandle } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'n006_action_0'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    n006: THREE.SkinnedMesh
    bone_1: THREE.Bone
    bone_2: THREE.Bone
    bone_3: THREE.Bone
    bone_4: THREE.Bone
    bone_5: THREE.Bone
  }
  materials: {
    n006: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default React.forwardRef(function n006(props: JSX.IntrinsicElements['group'], ref: React.Ref<{ actions: Record<ActionName, AnimationAction>, mesh: Group }>) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/models/n006.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
    
    const formattedAnimations = useAnimations(animations, group);
    useImperativeHandle(ref, () => ({ animations: formattedAnimations, group, nodes, materials }));
      return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="n006_armature">
          <primitive object={nodes.bone_1} />
          <primitive object={nodes.bone_2} />
          <primitive object={nodes.bone_3} />
          <primitive object={nodes.bone_4} />
          <primitive object={nodes.bone_5} />
          <skinnedMesh name="n006" geometry={nodes.n006.geometry} material={materials.n006} skeleton={nodes.n006.skeleton} />
        </group>
      </group>
    </group>
    ); })

useGLTF.preload('/models/n006.glb')
