/* eslint-disable */
// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./optimized/base/models/n014.gltf --types --keepgroups --exportdefault --output=./gltf/n014.tsx 
*/

import * as THREE from 'three'
import React, { useImperativeHandle } from 'react'
import { useGraph } from '@react-three/fiber'
import { useAnimations } from '@react-three/drei';
import { useFragmentedGLTFLoader } from '../useFragmentedGLTFLoader'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'n014_action_000'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    n014_mesh_0_mesh: THREE.SkinnedMesh
    n014_mesh_0_mesh_1: THREE.SkinnedMesh
    n014_mesh_0_mesh_2: THREE.SkinnedMesh
    n014_mesh_0_mesh_3: THREE.SkinnedMesh
    n014_mesh_1_mesh: THREE.SkinnedMesh
    n014_mesh_1_mesh_1: THREE.SkinnedMesh
    n014_mesh_2_mesh: THREE.SkinnedMesh
    n014_mesh_2_mesh_1: THREE.SkinnedMesh
    n014_mesh_3_mesh: THREE.SkinnedMesh
    n014_mesh_3_mesh_1: THREE.SkinnedMesh
    n014_mesh_4_mesh: THREE.SkinnedMesh
    n014_mesh_4_mesh_1: THREE.SkinnedMesh
    n014_mesh_5: THREE.SkinnedMesh
    n014_mesh_6: THREE.SkinnedMesh
    bone_0: THREE.Bone
  }
  materials: {
    n014_mesh_0_texture_0: THREE.MeshStandardMaterial
    n014_mesh_0_texture_1: THREE.MeshStandardMaterial
    n014_mesh_0_texture_2: THREE.MeshStandardMaterial
    n014_mesh_0_texture_3: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default React.forwardRef(function n014(props: JSX.IntrinsicElements['group'], ref: React.Ref<{ actions: Record<ActionName, AnimationAction>, mesh: Group }>) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useFragmentedGLTFLoader('n014', props.mapName)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)

 const formattedAnimations = useAnimations(animations, group);
 useImperativeHandle(ref, () => ({ animations: formattedAnimations, group, nodes, materials }));
   return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="n014_armature">
          <primitive object={nodes.bone_0} />
        </group>
        <group name="n014_mesh_0">
          <skinnedMesh name="n014_mesh_0_mesh" geometry={nodes.n014_mesh_0_mesh.geometry} material={materials.n014_mesh_0_texture_0} skeleton={nodes.n014_mesh_0_mesh.skeleton} />
          <skinnedMesh name="n014_mesh_0_mesh_1" geometry={nodes.n014_mesh_0_mesh_1.geometry} material={materials.n014_mesh_0_texture_1} skeleton={nodes.n014_mesh_0_mesh_1.skeleton} />
          <skinnedMesh name="n014_mesh_0_mesh_2" geometry={nodes.n014_mesh_0_mesh_2.geometry} material={materials.n014_mesh_0_texture_2} skeleton={nodes.n014_mesh_0_mesh_2.skeleton} />
          <skinnedMesh name="n014_mesh_0_mesh_3" geometry={nodes.n014_mesh_0_mesh_3.geometry} material={materials.n014_mesh_0_texture_3} skeleton={nodes.n014_mesh_0_mesh_3.skeleton} />
        </group>
        <group name="n014_mesh_1">
          <skinnedMesh name="n014_mesh_1_mesh" geometry={nodes.n014_mesh_1_mesh.geometry} material={materials.n014_mesh_0_texture_0} skeleton={nodes.n014_mesh_1_mesh.skeleton} />
          <skinnedMesh name="n014_mesh_1_mesh_1" geometry={nodes.n014_mesh_1_mesh_1.geometry} material={materials.n014_mesh_0_texture_2} skeleton={nodes.n014_mesh_1_mesh_1.skeleton} />
        </group>
        <group name="n014_mesh_2">
          <skinnedMesh name="n014_mesh_2_mesh" geometry={nodes.n014_mesh_2_mesh.geometry} material={materials.n014_mesh_0_texture_0} skeleton={nodes.n014_mesh_2_mesh.skeleton} />
          <skinnedMesh name="n014_mesh_2_mesh_1" geometry={nodes.n014_mesh_2_mesh_1.geometry} material={materials.n014_mesh_0_texture_2} skeleton={nodes.n014_mesh_2_mesh_1.skeleton} />
        </group>
        <group name="n014_mesh_3">
          <skinnedMesh name="n014_mesh_3_mesh" geometry={nodes.n014_mesh_3_mesh.geometry} material={materials.n014_mesh_0_texture_0} skeleton={nodes.n014_mesh_3_mesh.skeleton} />
          <skinnedMesh name="n014_mesh_3_mesh_1" geometry={nodes.n014_mesh_3_mesh_1.geometry} material={materials.n014_mesh_0_texture_1} skeleton={nodes.n014_mesh_3_mesh_1.skeleton} />
        </group>
        <group name="n014_mesh_4">
          <skinnedMesh name="n014_mesh_4_mesh" geometry={nodes.n014_mesh_4_mesh.geometry} material={materials.n014_mesh_0_texture_0} skeleton={nodes.n014_mesh_4_mesh.skeleton} />
          <skinnedMesh name="n014_mesh_4_mesh_1" geometry={nodes.n014_mesh_4_mesh_1.geometry} material={materials.n014_mesh_0_texture_1} skeleton={nodes.n014_mesh_4_mesh_1.skeleton} />
        </group>
        <skinnedMesh name="n014_mesh_5" geometry={nodes.n014_mesh_5.geometry} material={materials.n014_mesh_0_texture_2} skeleton={nodes.n014_mesh_5.skeleton} />
        <skinnedMesh name="n014_mesh_6" geometry={nodes.n014_mesh_6.geometry} material={materials.n014_mesh_0_texture_2} skeleton={nodes.n014_mesh_6.skeleton} />
      </group>
    </group>
 ); })

useFragmentedGLTFLoader.preload('n014')
