/* eslint-disable */
// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/n021.gltf --types --keepgroups --exportdefault --output=../gltf/n021.tsx 
*/

import * as THREE from 'three'
import React, { useImperativeHandle } from 'react'
import { useGraph } from '@react-three/fiber'
import { useAnimations } from '@react-three/drei';
import { useFragmentedGLTFLoader } from '../useFragmentedGLTFLoader'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'n021_action_000'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    n021_mesh: THREE.SkinnedMesh
    n021_mesh_1: THREE.SkinnedMesh
    bone_0: THREE.Bone
  }
  materials: {
    n021_texture_0: THREE.MeshStandardMaterial
    n021_texture_1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default React.forwardRef(function n021(props: JSX.IntrinsicElements['group'], ref: React.Ref<{ actions: Record<ActionName, AnimationAction>, mesh: Group }>) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useFragmentedGLTFLoader('n021', props.mapName)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)

 const formattedAnimations = useAnimations(animations, group);
 useImperativeHandle(ref, () => ({ animations: formattedAnimations, group, nodes, materials }));
   return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="n021_armature">
          <primitive object={nodes.bone_0} />
          <group name="n021">
            <skinnedMesh name="n021_mesh" geometry={nodes.n021_mesh.geometry} material={materials.n021_texture_0} skeleton={nodes.n021_mesh.skeleton} />
            <skinnedMesh name="n021_mesh_1" geometry={nodes.n021_mesh_1.geometry} material={materials.n021_texture_1} skeleton={nodes.n021_mesh_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
 ); })

useFragmentedGLTFLoader.preload('n021')
