/* eslint-disable */
// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/o020.gltf --types --keepgroups --exportdefault --output=../gltf/o020.tsx 
*/

import * as THREE from 'three'
import React, { useImperativeHandle } from 'react'
import { useGraph } from '@react-three/fiber'
import { useAnimations } from '@react-three/drei';
import { useFragmentedGLTFLoader } from '../useFragmentedGLTFLoader'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'o020_action_0'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    o020_mesh: THREE.SkinnedMesh
    o020_mesh_1: THREE.SkinnedMesh
    bone_0: THREE.Bone
  }
  materials: {
    o020_texture_0: THREE.MeshStandardMaterial
    o020_texture_1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default React.forwardRef(function o020(props: JSX.IntrinsicElements['group'], ref: React.Ref<{ actions: Record<ActionName, AnimationAction>, mesh: Group }>) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useFragmentedGLTFLoader('o020', props.mapName)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)

 const formattedAnimations = useAnimations(animations, group);
 useImperativeHandle(ref, () => ({ animations: formattedAnimations, group, nodes, materials }));
   return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="o020_armature" position={[0, 0, 0.707]}>
          <primitive object={nodes.bone_0} />
          <group name="o020">
            <skinnedMesh name="o020_mesh" geometry={nodes.o020_mesh.geometry} material={materials.o020_texture_0} skeleton={nodes.o020_mesh.skeleton} />
            <skinnedMesh name="o020_mesh_1" geometry={nodes.o020_mesh_1.geometry} material={materials.o020_texture_1} skeleton={nodes.o020_mesh_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
 ); })

useFragmentedGLTFLoader.preload('o020')
