/* eslint-disable */
// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/o028.glb --types --exportdefault --output=./gltf/o028.tsx 
*/

import * as THREE from 'three'
import React, { useImperativeHandle } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'o028_action_0' | 'o028_action_1' | 'o028_action_10' | 'o028_action_11' | 'o028_action_12' | 'o028_action_13' | 'o028_action_14' | 'o028_action_15' | 'o028_action_2' | 'o028_action_3' | 'o028_action_4' | 'o028_action_5' | 'o028_action_6' | 'o028_action_7' | 'o028_action_8' | 'o028_action_9'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    o028: THREE.SkinnedMesh
    bone_1: THREE.Bone
  }
  materials: {
    o028: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default React.forwardRef(function o028(props: JSX.IntrinsicElements['group'], ref: React.Ref<{ actions: Record<ActionName, AnimationAction>, mesh: Group }>) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/models/o028.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
    
    const formattedAnimations = useAnimations(animations, group);
    useImperativeHandle(ref, () => ({ animations: formattedAnimations, group, nodes, materials }));
      return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="o028_armature">
          <primitive object={nodes.bone_1} />
          <skinnedMesh name="o028" geometry={nodes.o028.geometry} material={materials.o028} skeleton={nodes.o028.skeleton} />
        </group>
      </group>
    </group>
    ); })

useGLTF.preload('/models/o028.glb')
