/* eslint-disable */
// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/o031.glb --types --exportdefault --output=./gltf/o031.tsx 
*/

import * as THREE from 'three'
import React, { useImperativeHandle } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'o031_action_0' | 'o031_action_1' | 'o031_action_10' | 'o031_action_11' | 'o031_action_12' | 'o031_action_13' | 'o031_action_14' | 'o031_action_15' | 'o031_action_16' | 'o031_action_2' | 'o031_action_3' | 'o031_action_4' | 'o031_action_5' | 'o031_action_6' | 'o031_action_7' | 'o031_action_8' | 'o031_action_9'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    o031: THREE.SkinnedMesh
    bone_1: THREE.Bone
  }
  materials: {
    o031: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default React.forwardRef(function o031(props: JSX.IntrinsicElements['group'], ref: React.Ref<{ actions: Record<ActionName, AnimationAction>, mesh: Group }>) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/models/o031.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
    
    const formattedAnimations = useAnimations(animations, group);
    useImperativeHandle(ref, () => ({ animations: formattedAnimations, group, nodes, materials }));
      return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="o031_armature">
          <primitive object={nodes.bone_1} />
          <skinnedMesh name="o031" geometry={nodes.o031.geometry} material={materials.o031} skeleton={nodes.o031.skeleton} />
        </group>
      </group>
    </group>
    ); })

useGLTF.preload('/models/o031.glb')
