/* eslint-disable */
// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/o202.gltf --types --keepgroups --exportdefault --output=./gltf/o202.tsx 
*/

import * as THREE from 'three'
import React, { useImperativeHandle } from 'react'
import { useGraph } from '@react-three/fiber'
import { useAnimations } from '@react-three/drei';
import { useFragmentedGLTFLoader } from '../useFragmentedGLTFLoader'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'o202_action_0'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    o202_mesh: THREE.SkinnedMesh
    o202_mesh_1: THREE.SkinnedMesh
    bone_0: THREE.Bone
  }
  materials: {
    o202_texture_0: THREE.MeshStandardMaterial
    o202_texture_1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default React.forwardRef(function o202(props: JSX.IntrinsicElements['group'], ref: React.Ref<{ actions: Record<ActionName, AnimationAction>, mesh: Group }>) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useFragmentedGLTFLoader('o202', props.mapName)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
    
    const formattedAnimations = useAnimations(animations, group);
    useImperativeHandle(ref, () => ({ animations: formattedAnimations, group, nodes, materials }));
      return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="o202_armature">
          <primitive object={nodes.bone_0} />
          <group name="o202">
            <skinnedMesh name="o202_mesh" geometry={nodes.o202_mesh.geometry} material={materials.o202_texture_0} skeleton={nodes.o202_mesh.skeleton} />
            <skinnedMesh name="o202_mesh_1" geometry={nodes.o202_mesh_1.geometry} material={materials.o202_texture_1} skeleton={nodes.o202_mesh_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
    ); })

useFragmentedGLTFLoader.preload('o202')
