/* eslint-disable */
// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/p001.gltf --types --keepgroups --exportdefault --output=../gltf/p001.tsx 
*/

import * as THREE from 'three'
import React, { useImperativeHandle } from 'react'
import { useGraph } from '@react-three/fiber'
import { useAnimations } from '@react-three/drei';
import { useFragmentedGLTFLoader } from '../useFragmentedGLTFLoader'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'p001_action_000' | 'p001_action_001' | 'p001_action_002' | 'p001_action_003'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    p001_mesh: THREE.SkinnedMesh
    p001_mesh_1: THREE.SkinnedMesh
    bone_0: THREE.Bone
  }
  materials: {
    p001_texture_0: THREE.MeshStandardMaterial
    p001_texture_1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default React.forwardRef(function p001(props: JSX.IntrinsicElements['group'], ref: React.Ref<{ actions: Record<ActionName, AnimationAction>, mesh: Group }>) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useFragmentedGLTFLoader('p001', props.mapName)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)

 const formattedAnimations = useAnimations(animations, group);
 useImperativeHandle(ref, () => ({ animations: formattedAnimations, group, nodes, materials }));
   return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="p001_armature" position={[0, 0, 0.83]}>
          <primitive object={nodes.bone_0} />
          <group name="p001">
            <skinnedMesh name="p001_mesh" geometry={nodes.p001_mesh.geometry} material={materials.p001_texture_0} skeleton={nodes.p001_mesh.skeleton} />
            <skinnedMesh name="p001_mesh_1" geometry={nodes.p001_mesh_1.geometry} material={materials.p001_texture_1} skeleton={nodes.p001_mesh_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
 ); })

useFragmentedGLTFLoader.preload('p001')
