/* eslint-disable */
// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/p012.gltf --types --keepgroups --exportdefault --output=./gltf/p012.tsx 
*/

import * as THREE from 'three'
import React, { useImperativeHandle } from 'react'
import { useGraph } from '@react-three/fiber'
import { useAnimations } from '@react-three/drei';
import { useFragmentedGLTFLoader } from '../useFragmentedGLTFLoader'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'p012_action_0' | 'p012_action_1' | 'p012_action_2' | 'p012_action_3' | 'p012_action_4' | 'p012_action_5' | 'p012_action_6' | 'p012_action_7' | 'p012_action_8'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    p012_mesh: THREE.SkinnedMesh
    p012_mesh_1: THREE.SkinnedMesh
    bone_0: THREE.Bone
  }
  materials: {
    p012_texture_0: THREE.MeshStandardMaterial
    p012_texture_1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default React.forwardRef(function p012(props: JSX.IntrinsicElements['group'], ref: React.Ref<{ actions: Record<ActionName, AnimationAction>, mesh: Group }>) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useFragmentedGLTFLoader('p012', props.mapName)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
    
    const formattedAnimations = useAnimations(animations, group);
    useImperativeHandle(ref, () => ({ animations: formattedAnimations, group, nodes, materials }));
      return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="p012_armature">
          <primitive object={nodes.bone_0} />
          <group name="p012">
            <skinnedMesh name="p012_mesh" geometry={nodes.p012_mesh.geometry} material={materials.p012_texture_0} skeleton={nodes.p012_mesh.skeleton} />
            <skinnedMesh name="p012_mesh_1" geometry={nodes.p012_mesh_1.geometry} material={materials.p012_texture_1} skeleton={nodes.p012_mesh_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
    ); })

useFragmentedGLTFLoader.preload('p012')
