export const CHAPTERS = {
  'Intro': {
    fieldId: 'start0',
    progress: 0,
    party: [0]
  },
  'First Laguna dream': {
    fieldId: 'testbl6',
    progress: 22,
    party: [8,9,10]
  },
  'Disk Two': {
    fieldId: 'testbl6',
    progress: 392,
  },
  'Fisherman\'s Horizon: landing': {
    fieldId: 'fhdeck1',
    progress: 610,
  },
  'Disk Three': {
    fieldId: 'testbl6',
    progress: 900,
  },
  'Esthar: arrival': {
    fieldId: 'ectake1',
    progress: 1900
  },
  'Shumi Village': {
    fieldId: 'tmdome1',
    progress: 2000,
  },
  'Approaching Lunatic Pandora': {
    fieldId: 'rgcock2',
    progress: 3850
  },
  'Disk Four': {
    fieldId: 'testbl6',
    progress: 900,
  },
  'The Castle': {
    fieldId: 'ffbrdg1',
    progress: 4020,
  },
}