export const CHAPTERS = {
  'The Landing': {
    fieldId: 'bvcar_1',
    progress: 0
  },
  'First Laguna dream': {
    fieldId: 'testbl6',
    progress: 22,
  },
  'Winhill': {
    fieldId: 'gfelone2',
    progress: 400
  },
  'Fisherman\'s Horizon: Occupation': {
    fieldId: 'fhtown22',
    progress: 651,
  },
  'Edea\'s House: On GFs': {
    fieldId: 'ehblan1',
    progress: 780
  },
  'NORG': {
    fieldId: 'norg',
    progress: 890
  },
  'Edea\'s House: Now': {
    fieldId: 'ehenter2',
    progress: 900
  },
  'Odine\'s Lab': {
    fieldId: 'epwork1',
    progress: 3606
  },
  'The Final Mission': {
    fieldId: 'rgcock2',
    progress: 3850
  },
  'The Castle: Anchor point': {
    fieldId: 'ehenter3',
    progress: 400
  }
}